export const mockListings: any[] = [
  {
    name: 'Rhybox',
    description:
      'convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia',
    category: 'Pool',
    amenities: 'TV',
    price: 502,
    recommendedGuestCount: 8,
    bedrooms: 2,
    beds: 6,
    baths: 2.2,
    imageUrl: 'http://dummyimage.com/174x100.png/cc0000/ffffff',
    reviews: {
      rating: 1,
      comment: 'A comment about my experience',
      userId: 17,
    },
    hostId: 11,
    street: '5061 Merchant Parkway',
    city: 'Columbus',
    state: 'Mississippi',
    zip: 83470,
    country: 'United States',
    address: {
      street: '5061 Merchant Parkway',
      city: 'Columbus',
      state: 'Mississippi',
      zip: 83470,
      country: 'United States',
    },
  },
  {
    name: 'Dynabox',
    description:
      'erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper',
    category: 'Desert',
    amenities: 'Netflix',
    price: 290,
    recommendedGuestCount: 18,
    bedrooms: 4,
    beds: 8,
    baths: 1.6,
    imageUrl: 'http://dummyimage.com/163x100.png/cc0000/ffffff',
    reviews: {
      rating: 2,
      comment: 'A comment about my experience',
      userId: 0,
    },
    hostId: 83,
    street: '5560 Fremont Hill',
    city: 'Chicago',
    state: 'Illinois',
    zip: 39056,
    country: 'United States',
    address: {
      street: '5560 Fremont Hill',
      city: 'Chicago',
      state: 'Illinois',
      zip: 39056,
      country: 'United States',
    },
  },
  {
    name: 'Buzzshare',
    description:
      'tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue',
    category: 'Castle',
    amenities: 'Stocked Fridge',
    price: 334,
    recommendedGuestCount: 13,
    bedrooms: 1,
    beds: 6,
    baths: 4.6,
    imageUrl: 'http://dummyimage.com/190x100.png/ff4444/ffffff',
    reviews: {
      rating: 1,
      comment: 'A comment about my experience',
      userId: 52,
    },
    hostId: 67,
    street: '83922 Caliangt Court',
    city: 'Honolulu',
    state: 'Hawaii',
    zip: 48650,
    country: 'United States',
    address: {
      street: '83922 Caliangt Court',
      city: 'Honolulu',
      state: 'Hawaii',
      zip: 48650,
      country: 'United States',
    },
  },
  {
    name: 'Zoombeat',
    description:
      'dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non',
    category: 'Beach',
    amenities: 'WiFi',
    price: 898,
    recommendedGuestCount: 3,
    bedrooms: 3,
    beds: 3,
    baths: 4.5,
    imageUrl: 'http://dummyimage.com/198x100.png/ff4444/ffffff',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 29,
    },
    hostId: 28,
    street: '2 Cody Terrace',
    city: 'Norman',
    state: 'Oklahoma',
    zip: 16438,
    country: 'United States',
    address: {
      street: '2 Cody Terrace',
      city: 'Norman',
      state: 'Oklahoma',
      zip: 16438,
      country: 'United States',
    },
  },
  {
    name: 'Kimia',
    description:
      'pede ullamcorper augue a suscipit nulla elit ac nulla sed vel',
    category: 'Desert',
    amenities: 'Stocked Fridge',
    price: 244,
    recommendedGuestCount: 11,
    bedrooms: 4,
    beds: 10,
    baths: 3.5,
    imageUrl: 'http://dummyimage.com/198x100.png/cc0000/ffffff',
    reviews: {
      rating: 1,
      comment: 'A comment about my experience',
      userId: 69,
    },
    hostId: 52,
    street: '35889 Manley Plaza',
    city: 'El Paso',
    state: 'Texas',
    zip: 66967,
    country: 'United States',
    address: {
      street: '35889 Manley Plaza',
      city: 'El Paso',
      state: 'Texas',
      zip: 66967,
      country: 'United States',
    },
  },
  {
    name: 'Dabvine',
    description:
      'in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices',
    category: 'Pool',
    amenities: 'Washing Machine/ Dryer',
    price: 125,
    recommendedGuestCount: 8,
    bedrooms: 1,
    beds: 4,
    baths: 3.1,
    imageUrl: 'http://dummyimage.com/126x100.png/dddddd/000000',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 18,
    },
    hostId: 4,
    street: '159 Moland Place',
    city: 'Houston',
    state: 'Texas',
    zip: 31149,
    country: 'United States',
    address: {
      street: '159 Moland Place',
      city: 'Houston',
      state: 'Texas',
      zip: 31149,
      country: 'United States',
    },
  },
  {
    name: 'Flashdog',
    description:
      'id mauris vulputate elementum nullam varius nulla facilisi cras non',
    category: 'Pool',
    amenities: 'Stocked Fridge',
    price: 164,
    recommendedGuestCount: 13,
    bedrooms: 2,
    beds: 10,
    baths: 1.8,
    imageUrl: 'http://dummyimage.com/116x100.png/ff4444/ffffff',
    reviews: {
      rating: 1,
      comment: 'A comment about my experience',
      userId: 42,
    },
    hostId: 58,
    street: '867 Lakeland Plaza',
    city: 'Bryan',
    state: 'Texas',
    zip: 28045,
    country: 'United States',
    address: {
      street: '867 Lakeland Plaza',
      city: 'Bryan',
      state: 'Texas',
      zip: 28045,
      country: 'United States',
    },
  },
  {
    name: 'Oyoloo',
    description:
      'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor',
    category: 'Pool',
    amenities: 'WiFi',
    price: 214,
    recommendedGuestCount: 19,
    bedrooms: 5,
    beds: 10,
    baths: 3.2,
    imageUrl: 'http://dummyimage.com/167x100.png/dddddd/000000',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 15,
    },
    hostId: 34,
    street: '8945 Summerview Drive',
    city: 'Seattle',
    state: 'Washington',
    zip: 43519,
    country: 'United States',
    address: {
      street: '8945 Summerview Drive',
      city: 'Seattle',
      state: 'Washington',
      zip: 43519,
      country: 'United States',
    },
  },
  {
    name: 'Trupe',
    description:
      'enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue',
    category: 'Castle',
    amenities: 'Dishwasher',
    price: 357,
    recommendedGuestCount: 2,
    bedrooms: 1,
    beds: 6,
    baths: 3.1,
    imageUrl: 'http://dummyimage.com/114x100.png/ff4444/ffffff',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 77,
    },
    hostId: 56,
    street: '96 Crownhardt Junction',
    city: 'Killeen',
    state: 'Texas',
    zip: 51262,
    country: 'United States',
    address: {
      street: '96 Crownhardt Junction',
      city: 'Killeen',
      state: 'Texas',
      zip: 51262,
      country: 'United States',
    },
  },
  {
    name: 'Wordtune',
    description:
      'iaculis diam erat fermentum justo nec condimentum neque sapien placerat',
    category: 'Desert',
    amenities: 'TV',
    price: 333,
    recommendedGuestCount: 17,
    bedrooms: 2,
    beds: 2,
    baths: 3.2,
    imageUrl: 'http://dummyimage.com/187x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 94,
    },
    hostId: 48,
    street: '01 Tomscot Point',
    city: 'Syracuse',
    state: 'New York',
    zip: 39031,
    country: 'United States',
    address: {
      street: '01 Tomscot Point',
      city: 'Syracuse',
      state: 'New York',
      zip: 39031,
      country: 'United States',
    },
  },
  {
    name: 'Bubblemix',
    description:
      'posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis',
    category: 'Desert',
    amenities: 'WiFi',
    price: 745,
    recommendedGuestCount: 9,
    bedrooms: 3,
    beds: 9,
    baths: 3.0,
    imageUrl: 'http://dummyimage.com/248x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 98,
    },
    hostId: 60,
    street: '8855 Shopko Way',
    city: 'Columbus',
    state: 'Ohio',
    zip: 34308,
    country: 'United States',
    address: {
      street: '8855 Shopko Way',
      city: 'Columbus',
      state: 'Ohio',
      zip: 34308,
      country: 'United States',
    },
  },
  {
    name: 'Bluezoom',
    description:
      'duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam',
    category: 'Pool',
    amenities: 'TV',
    price: 566,
    recommendedGuestCount: 11,
    bedrooms: 2,
    beds: 7,
    baths: 1.3,
    imageUrl: 'http://dummyimage.com/196x100.png/cc0000/ffffff',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 47,
    },
    hostId: 84,
    street: '69 Dakota Place',
    city: 'Clearwater',
    state: 'Florida',
    zip: 77348,
    country: 'United States',
    address: {
      street: '69 Dakota Place',
      city: 'Clearwater',
      state: 'Florida',
      zip: 77348,
      country: 'United States',
    },
  },
  {
    name: 'Skalith',
    description:
      'sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan',
    category: 'Desert',
    amenities: 'Security Cameras',
    price: 453,
    recommendedGuestCount: 6,
    bedrooms: 5,
    beds: 8,
    baths: 4.8,
    imageUrl: 'http://dummyimage.com/228x100.png/ff4444/ffffff',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 86,
    },
    hostId: 64,
    street: '589 Charing Cross Trail',
    city: 'Roanoke',
    state: 'Virginia',
    zip: 90545,
    country: 'United States',
    address: {
      street: '589 Charing Cross Trail',
      city: 'Roanoke',
      state: 'Virginia',
      zip: 90545,
      country: 'United States',
    },
  },
  {
    name: 'Yamia',
    description:
      'in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien',
    category: 'Desert',
    amenities: 'Cable',
    price: 742,
    recommendedGuestCount: 9,
    bedrooms: 4,
    beds: 7,
    baths: 2.1,
    imageUrl: 'http://dummyimage.com/115x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 35,
    },
    hostId: 62,
    street: '0 Superior Pass',
    city: 'Tampa',
    state: 'Florida',
    zip: 26132,
    country: 'United States',
    address: {
      street: '0 Superior Pass',
      city: 'Tampa',
      state: 'Florida',
      zip: 26132,
      country: 'United States',
    },
  },
  {
    name: 'Skippad',
    description:
      'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet',
    category: 'Castle',
    amenities: 'Netflix',
    price: 169,
    recommendedGuestCount: 1,
    bedrooms: 5,
    beds: 5,
    baths: 3.0,
    imageUrl: 'http://dummyimage.com/178x100.png/dddddd/000000',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 31,
    },
    hostId: 29,
    street: '61326 Duke Trail',
    city: 'Birmingham',
    state: 'Alabama',
    zip: 43051,
    country: 'United States',
    address: {
      street: '61326 Duke Trail',
      city: 'Birmingham',
      state: 'Alabama',
      zip: 43051,
      country: 'United States',
    },
  },
  {
    name: 'Vinte',
    description:
      'ut erat id mauris vulputate elementum nullam varius nulla facilisi cras',
    category: 'Beach',
    amenities: 'Cable',
    price: 431,
    recommendedGuestCount: 8,
    bedrooms: 4,
    beds: 5,
    baths: 2.7,
    imageUrl: 'http://dummyimage.com/135x100.png/dddddd/000000',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 15,
    },
    hostId: 89,
    street: '4 Esch Street',
    city: 'Charleston',
    state: 'West Virginia',
    zip: 45918,
    country: 'United States',
    address: {
      street: '4 Esch Street',
      city: 'Charleston',
      state: 'West Virginia',
      zip: 45918,
      country: 'United States',
    },
  },
  {
    name: 'Innojam',
    description:
      'lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo',
    category: 'Castle',
    amenities: 'Washing Machine/ Dryer',
    price: 529,
    recommendedGuestCount: 17,
    bedrooms: 3,
    beds: 1,
    baths: 1.9,
    imageUrl: 'http://dummyimage.com/143x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 47,
    },
    hostId: 62,
    street: '470 Superior Lane',
    city: 'Springfield',
    state: 'Virginia',
    zip: 86655,
    country: 'United States',
    address: {
      street: '470 Superior Lane',
      city: 'Springfield',
      state: 'Virginia',
      zip: 86655,
      country: 'United States',
    },
  },
  {
    name: 'Trilia',
    description:
      'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit',
    category: 'Pool',
    amenities: 'TV',
    price: 880,
    recommendedGuestCount: 10,
    bedrooms: 5,
    beds: 9,
    baths: 1.6,
    imageUrl: 'http://dummyimage.com/135x100.png/dddddd/000000',
    reviews: {
      rating: 2,
      comment: 'A comment about my experience',
      userId: 52,
    },
    hostId: 28,
    street: '85849 David Hill',
    city: 'Memphis',
    state: 'Tennessee',
    zip: 88702,
    country: 'United States',
    address: {
      street: '85849 David Hill',
      city: 'Memphis',
      state: 'Tennessee',
      zip: 88702,
      country: 'United States',
    },
  },
  {
    name: 'Rhyloo',
    description:
      'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien',
    category: 'Beach',
    amenities: 'Dishwasher',
    price: 662,
    recommendedGuestCount: 7,
    bedrooms: 1,
    beds: 5,
    baths: 2.0,
    imageUrl: 'http://dummyimage.com/143x100.png/cc0000/ffffff',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 10,
    },
    hostId: 74,
    street: '684 Stone Corner Hill',
    city: 'Roanoke',
    state: 'Virginia',
    zip: 72244,
    country: 'United States',
    address: {
      street: '684 Stone Corner Hill',
      city: 'Roanoke',
      state: 'Virginia',
      zip: 72244,
      country: 'United States',
    },
  },
  {
    name: 'Lazz',
    description:
      'felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec',
    category: 'Woods',
    amenities: 'Dishwasher',
    price: 167,
    recommendedGuestCount: 8,
    bedrooms: 5,
    beds: 3,
    baths: 4.1,
    imageUrl: 'http://dummyimage.com/103x100.png/dddddd/000000',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 24,
    },
    hostId: 9,
    street: '2 Harbort Court',
    city: 'Dayton',
    state: 'Ohio',
    zip: 60185,
    country: 'United States',
    address: {
      street: '2 Harbort Court',
      city: 'Dayton',
      state: 'Ohio',
      zip: 60185,
      country: 'United States',
    },
  },
  {
    name: 'Jabbersphere',
    description:
      'vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam',
    category: 'Castle',
    amenities: 'Cable',
    price: 561,
    recommendedGuestCount: 20,
    bedrooms: 4,
    beds: 6,
    baths: 2.9,
    imageUrl: 'http://dummyimage.com/118x100.png/dddddd/000000',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 22,
    },
    hostId: 71,
    street: '88690 Dorton Plaza',
    city: 'Omaha',
    state: 'Nebraska',
    zip: 85334,
    country: 'United States',
    address: {
      street: '88690 Dorton Plaza',
      city: 'Omaha',
      state: 'Nebraska',
      zip: 85334,
      country: 'United States',
    },
  },
  {
    name: 'Twimbo',
    description:
      'aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis',
    category: 'Woods',
    amenities: 'Dishwasher',
    price: 931,
    recommendedGuestCount: 10,
    bedrooms: 5,
    beds: 10,
    baths: 3.8,
    imageUrl: 'http://dummyimage.com/102x100.png/cc0000/ffffff',
    reviews: {
      rating: 1,
      comment: 'A comment about my experience',
      userId: 22,
    },
    hostId: 100,
    street: '4086 Fordem Crossing',
    city: 'Elizabeth',
    state: 'New Jersey',
    zip: 15927,
    country: 'United States',
    address: {
      street: '4086 Fordem Crossing',
      city: 'Elizabeth',
      state: 'New Jersey',
      zip: 15927,
      country: 'United States',
    },
  },
  {
    name: 'Vinte',
    description: 'aenean sit amet justo morbi ut odio cras mi pede',
    category: 'Desert',
    amenities: 'TV',
    price: 835,
    recommendedGuestCount: 6,
    bedrooms: 4,
    beds: 7,
    baths: 1.0,
    imageUrl: 'http://dummyimage.com/194x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 14,
    },
    hostId: 57,
    street: '95 Mayer Road',
    city: 'Lees Summit',
    state: 'Missouri',
    zip: 13191,
    country: 'United States',
    address: {
      street: '95 Mayer Road',
      city: 'Lees Summit',
      state: 'Missouri',
      zip: 13191,
      country: 'United States',
    },
  },
  {
    name: 'Oyoloo',
    description:
      'curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor',
    category: 'Beach',
    amenities: 'Washing Machine/ Dryer',
    price: 213,
    recommendedGuestCount: 19,
    bedrooms: 3,
    beds: 2,
    baths: 4.7,
    imageUrl: 'http://dummyimage.com/211x100.png/cc0000/ffffff',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 80,
    },
    hostId: 38,
    street: '7 Heath Street',
    city: 'Wichita',
    state: 'Kansas',
    zip: 98997,
    country: 'United States',
    address: {
      street: '7 Heath Street',
      city: 'Wichita',
      state: 'Kansas',
      zip: 98997,
      country: 'United States',
    },
  },
  {
    name: 'Skalith',
    description:
      'viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis',
    category: 'Castle',
    amenities: 'WiFi',
    price: 607,
    recommendedGuestCount: 4,
    bedrooms: 5,
    beds: 7,
    baths: 1.9,
    imageUrl: 'http://dummyimage.com/247x100.png/cc0000/ffffff',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 1,
    },
    hostId: 39,
    street: '0713 American Ash Street',
    city: 'Amarillo',
    state: 'Texas',
    zip: 91358,
    country: 'United States',
    address: {
      street: '0713 American Ash Street',
      city: 'Amarillo',
      state: 'Texas',
      zip: 91358,
      country: 'United States',
    },
  },
  {
    name: 'Oyoba',
    description:
      'rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel',
    category: 'Castle',
    amenities: 'Cable',
    price: 311,
    recommendedGuestCount: 14,
    bedrooms: 2,
    beds: 2,
    baths: 3.5,
    imageUrl: 'http://dummyimage.com/132x100.png/cc0000/ffffff',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 46,
    },
    hostId: 47,
    street: '76 Havey Plaza',
    city: 'Fort Worth',
    state: 'Texas',
    zip: 76703,
    country: 'United States',
    address: {
      street: '76 Havey Plaza',
      city: 'Fort Worth',
      state: 'Texas',
      zip: 76703,
      country: 'United States',
    },
  },
  {
    name: 'Cogidoo',
    description:
      'pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in',
    category: 'Castle',
    amenities: 'Washing Machine/ Dryer',
    price: 697,
    recommendedGuestCount: 4,
    bedrooms: 1,
    beds: 8,
    baths: 2.1,
    imageUrl: 'http://dummyimage.com/168x100.png/ff4444/ffffff',
    reviews: {
      rating: 2,
      comment: 'A comment about my experience',
      userId: 89,
    },
    hostId: 32,
    street: '687 Bonner Parkway',
    city: 'Boston',
    state: 'Massachusetts',
    zip: 79676,
    country: 'United States',
    address: {
      street: '687 Bonner Parkway',
      city: 'Boston',
      state: 'Massachusetts',
      zip: 79676,
      country: 'United States',
    },
  },
  {
    name: 'Blogpad',
    description:
      'luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper',
    category: 'Desert',
    amenities: 'Cable',
    price: 265,
    recommendedGuestCount: 2,
    bedrooms: 3,
    beds: 9,
    baths: 2.1,
    imageUrl: 'http://dummyimage.com/186x100.png/dddddd/000000',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 24,
    },
    hostId: 29,
    street: '2633 Holmberg Center',
    city: 'Denver',
    state: 'Colorado',
    zip: 66209,
    country: 'United States',
    address: {
      street: '2633 Holmberg Center',
      city: 'Denver',
      state: 'Colorado',
      zip: 66209,
      country: 'United States',
    },
  },
  {
    name: 'Twimm',
    description:
      'leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede',
    category: 'Woods',
    amenities: 'TV',
    price: 492,
    recommendedGuestCount: 8,
    bedrooms: 3,
    beds: 1,
    baths: 4.3,
    imageUrl: 'http://dummyimage.com/194x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 39,
    },
    hostId: 92,
    street: '81081 Logan Place',
    city: 'Charleston',
    state: 'West Virginia',
    zip: 79742,
    country: 'United States',
    address: {
      street: '81081 Logan Place',
      city: 'Charleston',
      state: 'West Virginia',
      zip: 79742,
      country: 'United States',
    },
  },
  {
    name: 'Camido',
    description:
      'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi',
    category: 'Pool',
    amenities: 'Cable',
    price: 244,
    recommendedGuestCount: 15,
    bedrooms: 1,
    beds: 2,
    baths: 3.5,
    imageUrl: 'http://dummyimage.com/174x100.png/ff4444/ffffff',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 9,
    },
    hostId: 74,
    street: '277 Stoughton Pass',
    city: 'Cincinnati',
    state: 'Ohio',
    zip: 25456,
    country: 'United States',
    address: {
      street: '277 Stoughton Pass',
      city: 'Cincinnati',
      state: 'Ohio',
      zip: 25456,
      country: 'United States',
    },
  },
  {
    name: 'Ooba',
    description:
      'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec',
    category: 'Pool',
    amenities: 'WiFi',
    price: 763,
    recommendedGuestCount: 3,
    bedrooms: 4,
    beds: 5,
    baths: 3.4,
    imageUrl: 'http://dummyimage.com/156x100.png/ff4444/ffffff',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 29,
    },
    hostId: 9,
    street: '70832 High Crossing Alley',
    city: 'Toledo',
    state: 'Ohio',
    zip: 79459,
    country: 'United States',
    address: {
      street: '70832 High Crossing Alley',
      city: 'Toledo',
      state: 'Ohio',
      zip: 79459,
      country: 'United States',
    },
  },
  {
    name: 'Voolia',
    description:
      'lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a',
    category: 'Beach',
    amenities: 'Dishwasher',
    price: 362,
    recommendedGuestCount: 1,
    bedrooms: 3,
    beds: 4,
    baths: 4.7,
    imageUrl: 'http://dummyimage.com/203x100.png/cc0000/ffffff',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 80,
    },
    hostId: 69,
    street: '1753 Thompson Way',
    city: 'Corpus Christi',
    state: 'Texas',
    zip: 51304,
    country: 'United States',
    address: {
      street: '1753 Thompson Way',
      city: 'Corpus Christi',
      state: 'Texas',
      zip: 51304,
      country: 'United States',
    },
  },
  {
    name: 'Jabbersphere',
    description:
      'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac',
    category: 'Beach',
    amenities: 'Netflix',
    price: 132,
    recommendedGuestCount: 15,
    bedrooms: 4,
    beds: 1,
    baths: 4.0,
    imageUrl: 'http://dummyimage.com/151x100.png/ff4444/ffffff',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 71,
    },
    hostId: 26,
    street: '40 Maple Wood Street',
    city: 'Hagerstown',
    state: 'Maryland',
    zip: 71769,
    country: 'United States',
    address: {
      street: '40 Maple Wood Street',
      city: 'Hagerstown',
      state: 'Maryland',
      zip: 71769,
      country: 'United States',
    },
  },
  {
    name: 'Kare',
    description:
      'sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo',
    category: 'Woods',
    amenities: 'WiFi',
    price: 535,
    recommendedGuestCount: 9,
    bedrooms: 1,
    beds: 2,
    baths: 2.5,
    imageUrl: 'http://dummyimage.com/185x100.png/ff4444/ffffff',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 68,
    },
    hostId: 8,
    street: '2678 Haas Circle',
    city: 'Alexandria',
    state: 'Virginia',
    zip: 57727,
    country: 'United States',
    address: {
      street: '2678 Haas Circle',
      city: 'Alexandria',
      state: 'Virginia',
      zip: 57727,
      country: 'United States',
    },
  },
  {
    name: 'Wordware',
    description:
      'nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo',
    category: 'Pool',
    amenities: 'Netflix',
    price: 577,
    recommendedGuestCount: 17,
    bedrooms: 4,
    beds: 9,
    baths: 2.9,
    imageUrl: 'http://dummyimage.com/138x100.png/cc0000/ffffff',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 73,
    },
    hostId: 99,
    street: '5911 Elmside Lane',
    city: 'Boise',
    state: 'Idaho',
    zip: 62471,
    country: 'United States',
    address: {
      street: '5911 Elmside Lane',
      city: 'Boise',
      state: 'Idaho',
      zip: 62471,
      country: 'United States',
    },
  },
  {
    name: 'Blogtag',
    description:
      'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat',
    category: 'Castle',
    amenities: 'Dishwasher',
    price: 418,
    recommendedGuestCount: 11,
    bedrooms: 4,
    beds: 2,
    baths: 2.2,
    imageUrl: 'http://dummyimage.com/131x100.png/dddddd/000000',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 9,
    },
    hostId: 42,
    street: '05833 Artisan Way',
    city: 'Boston',
    state: 'Massachusetts',
    zip: 35700,
    country: 'United States',
    address: {
      street: '05833 Artisan Way',
      city: 'Boston',
      state: 'Massachusetts',
      zip: 35700,
      country: 'United States',
    },
  },
  {
    name: 'Twiyo',
    description:
      'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla',
    category: 'Beach',
    amenities: 'Cable',
    price: 736,
    recommendedGuestCount: 18,
    bedrooms: 3,
    beds: 8,
    baths: 1.3,
    imageUrl: 'http://dummyimage.com/182x100.png/cc0000/ffffff',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 73,
    },
    hostId: 46,
    street: '913 Almo Parkway',
    city: 'Flushing',
    state: 'New York',
    zip: 65922,
    country: 'United States',
    address: {
      street: '913 Almo Parkway',
      city: 'Flushing',
      state: 'New York',
      zip: 65922,
      country: 'United States',
    },
  },
  {
    name: 'Jabberbean',
    description:
      'in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum',
    category: 'Beach',
    amenities: 'Washing Machine/ Dryer',
    price: 905,
    recommendedGuestCount: 1,
    bedrooms: 2,
    beds: 1,
    baths: 3.0,
    imageUrl: 'http://dummyimage.com/158x100.png/dddddd/000000',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 48,
    },
    hostId: 35,
    street: '267 Old Gate Trail',
    city: 'Amarillo',
    state: 'Texas',
    zip: 75395,
    country: 'United States',
    address: {
      street: '267 Old Gate Trail',
      city: 'Amarillo',
      state: 'Texas',
      zip: 75395,
      country: 'United States',
    },
  },
  {
    name: 'Photolist',
    description:
      'etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus',
    category: 'Pool',
    amenities: 'TV',
    price: 963,
    recommendedGuestCount: 3,
    bedrooms: 4,
    beds: 1,
    baths: 3.3,
    imageUrl: 'http://dummyimage.com/129x100.png/cc0000/ffffff',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 73,
    },
    hostId: 35,
    street: '8 West Road',
    city: 'Milwaukee',
    state: 'Wisconsin',
    zip: 64759,
    country: 'United States',
    address: {
      street: '8 West Road',
      city: 'Milwaukee',
      state: 'Wisconsin',
      zip: 64759,
      country: 'United States',
    },
  },
  {
    name: 'Twinder',
    description:
      'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque',
    category: 'Pool',
    amenities: 'Security Cameras',
    price: 437,
    recommendedGuestCount: 14,
    bedrooms: 2,
    beds: 1,
    baths: 2.1,
    imageUrl: 'http://dummyimage.com/187x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 19,
    },
    hostId: 25,
    street: '6463 Pepper Wood Drive',
    city: 'Des Moines',
    state: 'Iowa',
    zip: 29489,
    country: 'United States',
    address: {
      street: '6463 Pepper Wood Drive',
      city: 'Des Moines',
      state: 'Iowa',
      zip: 29489,
      country: 'United States',
    },
  },
  {
    name: 'Avamba',
    description:
      'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo',
    category: 'Pool',
    amenities: 'Dishwasher',
    price: 103,
    recommendedGuestCount: 14,
    bedrooms: 4,
    beds: 1,
    baths: 4.1,
    imageUrl: 'http://dummyimage.com/166x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 55,
    },
    hostId: 57,
    street: '7 Springview Court',
    city: 'Fullerton',
    state: 'California',
    zip: 51731,
    country: 'United States',
    address: {
      street: '7 Springview Court',
      city: 'Fullerton',
      state: 'California',
      zip: 51731,
      country: 'United States',
    },
  },
  {
    name: 'Quaxo',
    description:
      'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui',
    category: 'Desert',
    amenities: 'Cable',
    price: 414,
    recommendedGuestCount: 8,
    bedrooms: 4,
    beds: 7,
    baths: 1.1,
    imageUrl: 'http://dummyimage.com/107x100.png/ff4444/ffffff',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 81,
    },
    hostId: 98,
    street: '24 Continental Crossing',
    city: 'Kansas City',
    state: 'Kansas',
    zip: 27248,
    country: 'United States',
    address: {
      street: '24 Continental Crossing',
      city: 'Kansas City',
      state: 'Kansas',
      zip: 27248,
      country: 'United States',
    },
  },
  {
    name: 'Vinte',
    description:
      'posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed',
    category: 'Beach',
    amenities: 'Dishwasher',
    price: 140,
    recommendedGuestCount: 6,
    bedrooms: 1,
    beds: 3,
    baths: 1.1,
    imageUrl: 'http://dummyimage.com/200x100.png/cc0000/ffffff',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 5,
    },
    hostId: 51,
    street: '8 Lakewood Drive',
    city: 'Santa Cruz',
    state: 'California',
    zip: 65672,
    country: 'United States',
    address: {
      street: '8 Lakewood Drive',
      city: 'Santa Cruz',
      state: 'California',
      zip: 65672,
      country: 'United States',
    },
  },
  {
    name: 'Skinder',
    description:
      'turpis adipiscing lorem vitae mattis nibh ligula nec sem duis',
    category: 'Desert',
    amenities: 'Washing Machine/ Dryer',
    price: 414,
    recommendedGuestCount: 9,
    bedrooms: 5,
    beds: 5,
    baths: 1.6,
    imageUrl: 'http://dummyimage.com/169x100.png/cc0000/ffffff',
    reviews: {
      rating: 1,
      comment: 'A comment about my experience',
      userId: 52,
    },
    hostId: 82,
    street: '2 Brentwood Crossing',
    city: 'Sacramento',
    state: 'California',
    zip: 62661,
    country: 'United States',
    address: {
      street: '2 Brentwood Crossing',
      city: 'Sacramento',
      state: 'California',
      zip: 62661,
      country: 'United States',
    },
  },
  {
    name: 'Quaxo',
    description:
      'elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante',
    category: 'Desert',
    amenities: 'Cable',
    price: 627,
    recommendedGuestCount: 14,
    bedrooms: 5,
    beds: 7,
    baths: 5.0,
    imageUrl: 'http://dummyimage.com/139x100.png/ff4444/ffffff',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 50,
    },
    hostId: 13,
    street: '5 4th Plaza',
    city: 'Detroit',
    state: 'Michigan',
    zip: 93530,
    country: 'United States',
    address: {
      street: '5 4th Plaza',
      city: 'Detroit',
      state: 'Michigan',
      zip: 93530,
      country: 'United States',
    },
  },
  {
    name: 'Jabberstorm',
    description:
      'ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient',
    category: 'Desert',
    amenities: 'Stocked Fridge',
    price: 695,
    recommendedGuestCount: 1,
    bedrooms: 2,
    beds: 1,
    baths: 3.5,
    imageUrl: 'http://dummyimage.com/143x100.png/dddddd/000000',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 43,
    },
    hostId: 98,
    street: '69646 Declaration Park',
    city: 'Boise',
    state: 'Idaho',
    zip: 63809,
    country: 'United States',
    address: {
      street: '69646 Declaration Park',
      city: 'Boise',
      state: 'Idaho',
      zip: 63809,
      country: 'United States',
    },
  },
  {
    name: 'Jetpulse',
    description:
      'metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra',
    category: 'Woods',
    amenities: 'WiFi',
    price: 394,
    recommendedGuestCount: 1,
    bedrooms: 5,
    beds: 7,
    baths: 1.7,
    imageUrl: 'http://dummyimage.com/107x100.png/ff4444/ffffff',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 34,
    },
    hostId: 43,
    street: '9 Del Mar Center',
    city: 'Orlando',
    state: 'Florida',
    zip: 47160,
    country: 'United States',
    address: {
      street: '9 Del Mar Center',
      city: 'Orlando',
      state: 'Florida',
      zip: 47160,
      country: 'United States',
    },
  },
  {
    name: 'Realcube',
    description:
      'ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor',
    category: 'Beach',
    amenities: 'Washing Machine/ Dryer',
    price: 787,
    recommendedGuestCount: 12,
    bedrooms: 2,
    beds: 2,
    baths: 1.1,
    imageUrl: 'http://dummyimage.com/125x100.png/ff4444/ffffff',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 67,
    },
    hostId: 64,
    street: '57746 Clarendon Crossing',
    city: 'Monroe',
    state: 'Louisiana',
    zip: 49251,
    country: 'United States',
    address: {
      street: '57746 Clarendon Crossing',
      city: 'Monroe',
      state: 'Louisiana',
      zip: 49251,
      country: 'United States',
    },
  },
  {
    name: 'Meetz',
    description:
      'ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere',
    category: 'Beach',
    amenities: 'WiFi',
    price: 678,
    recommendedGuestCount: 4,
    bedrooms: 4,
    beds: 4,
    baths: 2.7,
    imageUrl: 'http://dummyimage.com/117x100.png/dddddd/000000',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 90,
    },
    hostId: 8,
    street: '367 Di Loreto Crossing',
    city: 'Miami',
    state: 'Florida',
    zip: 43183,
    country: 'United States',
    address: {
      street: '367 Di Loreto Crossing',
      city: 'Miami',
      state: 'Florida',
      zip: 43183,
      country: 'United States',
    },
  },
  {
    name: 'JumpXS',
    description:
      'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus',
    category: 'Castle',
    amenities: 'Cable',
    price: 719,
    recommendedGuestCount: 9,
    bedrooms: 5,
    beds: 4,
    baths: 1.6,
    imageUrl: 'http://dummyimage.com/232x100.png/cc0000/ffffff',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 0,
    },
    hostId: 11,
    street: '85615 Ronald Regan Junction',
    city: 'Seattle',
    state: 'Washington',
    zip: 15187,
    country: 'United States',
    address: {
      street: '85615 Ronald Regan Junction',
      city: 'Seattle',
      state: 'Washington',
      zip: 15187,
      country: 'United States',
    },
  },
  {
    name: 'Jabberstorm',
    description:
      'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac',
    category: 'Castle',
    amenities: 'Dishwasher',
    price: 686,
    recommendedGuestCount: 20,
    bedrooms: 1,
    beds: 2,
    baths: 4.0,
    imageUrl: 'http://dummyimage.com/227x100.png/dddddd/000000',
    reviews: {
      rating: 1,
      comment: 'A comment about my experience',
      userId: 9,
    },
    hostId: 17,
    street: '366 Hazelcrest Lane',
    city: 'Fresno',
    state: 'California',
    zip: 62224,
    country: 'United States',
    address: {
      street: '366 Hazelcrest Lane',
      city: 'Fresno',
      state: 'California',
      zip: 62224,
      country: 'United States',
    },
  },
  {
    name: 'Mudo',
    description:
      'et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet',
    category: 'Castle',
    amenities: 'Dishwasher',
    price: 254,
    recommendedGuestCount: 1,
    bedrooms: 1,
    beds: 6,
    baths: 2.9,
    imageUrl: 'http://dummyimage.com/103x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 7,
    },
    hostId: 24,
    street: '9401 Dexter Way',
    city: 'Chicago',
    state: 'Illinois',
    zip: 15419,
    country: 'United States',
    address: {
      street: '9401 Dexter Way',
      city: 'Chicago',
      state: 'Illinois',
      zip: 15419,
      country: 'United States',
    },
  },
  {
    name: 'Skipfire',
    description:
      'at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel',
    category: 'Beach',
    amenities: 'Dishwasher',
    price: 131,
    recommendedGuestCount: 7,
    bedrooms: 5,
    beds: 6,
    baths: 4.4,
    imageUrl: 'http://dummyimage.com/238x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 82,
    },
    hostId: 13,
    street: '728 Hazelcrest Parkway',
    city: 'San Diego',
    state: 'California',
    zip: 42770,
    country: 'United States',
    address: {
      street: '728 Hazelcrest Parkway',
      city: 'San Diego',
      state: 'California',
      zip: 42770,
      country: 'United States',
    },
  },
  {
    name: 'Edgetag',
    description:
      'elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet',
    category: 'Castle',
    amenities: 'WiFi',
    price: 604,
    recommendedGuestCount: 11,
    bedrooms: 2,
    beds: 3,
    baths: 4.5,
    imageUrl: 'http://dummyimage.com/181x100.png/dddddd/000000',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 81,
    },
    hostId: 97,
    street: '63936 Division Plaza',
    city: 'Lakewood',
    state: 'Washington',
    zip: 91029,
    country: 'United States',
    address: {
      street: '63936 Division Plaza',
      city: 'Lakewood',
      state: 'Washington',
      zip: 91029,
      country: 'United States',
    },
  },
  {
    name: 'Skiptube',
    description:
      'velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus',
    category: 'Castle',
    amenities: 'Washing Machine/ Dryer',
    price: 721,
    recommendedGuestCount: 7,
    bedrooms: 3,
    beds: 8,
    baths: 4.2,
    imageUrl: 'http://dummyimage.com/200x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 62,
    },
    hostId: 31,
    street: '287 East Center',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    zip: 10963,
    country: 'United States',
    address: {
      street: '287 East Center',
      city: 'Philadelphia',
      state: 'Pennsylvania',
      zip: 10963,
      country: 'United States',
    },
  },
  {
    name: 'Linkbuzz',
    description:
      'etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem',
    category: 'Castle',
    amenities: 'Netflix',
    price: 261,
    recommendedGuestCount: 5,
    bedrooms: 5,
    beds: 2,
    baths: 1.5,
    imageUrl: 'http://dummyimage.com/208x100.png/dddddd/000000',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 92,
    },
    hostId: 23,
    street: '31 Westend Center',
    city: 'Colorado Springs',
    state: 'Colorado',
    zip: 59162,
    country: 'United States',
    address: {
      street: '31 Westend Center',
      city: 'Colorado Springs',
      state: 'Colorado',
      zip: 59162,
      country: 'United States',
    },
  },
  {
    name: 'Photobug',
    description:
      'ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus',
    category: 'Pool',
    amenities: 'Netflix',
    price: 848,
    recommendedGuestCount: 7,
    bedrooms: 5,
    beds: 9,
    baths: 2.9,
    imageUrl: 'http://dummyimage.com/205x100.png/ff4444/ffffff',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 14,
    },
    hostId: 82,
    street: '981 Quincy Trail',
    city: 'Portland',
    state: 'Maine',
    zip: 86725,
    country: 'United States',
    address: {
      street: '981 Quincy Trail',
      city: 'Portland',
      state: 'Maine',
      zip: 86725,
      country: 'United States',
    },
  },
  {
    name: 'Muxo',
    description:
      'nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis',
    category: 'Desert',
    amenities: 'Dishwasher',
    price: 715,
    recommendedGuestCount: 8,
    bedrooms: 2,
    beds: 3,
    baths: 2.5,
    imageUrl: 'http://dummyimage.com/173x100.png/ff4444/ffffff',
    reviews: {
      rating: 2,
      comment: 'A comment about my experience',
      userId: 94,
    },
    hostId: 90,
    street: '61 Chinook Lane',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    zip: 52127,
    country: 'United States',
    address: {
      street: '61 Chinook Lane',
      city: 'Pittsburgh',
      state: 'Pennsylvania',
      zip: 52127,
      country: 'United States',
    },
  },
  {
    name: 'Voomm',
    description:
      'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue',
    category: 'Woods',
    amenities: 'Stocked Fridge',
    price: 715,
    recommendedGuestCount: 6,
    bedrooms: 3,
    beds: 1,
    baths: 1.7,
    imageUrl: 'http://dummyimage.com/138x100.png/ff4444/ffffff',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 86,
    },
    hostId: 59,
    street: '2662 1st Lane',
    city: 'Colorado Springs',
    state: 'Colorado',
    zip: 43346,
    country: 'United States',
    address: {
      street: '2662 1st Lane',
      city: 'Colorado Springs',
      state: 'Colorado',
      zip: 43346,
      country: 'United States',
    },
  },
  {
    name: 'Meedoo',
    description:
      'augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea',
    category: 'Desert',
    amenities: 'TV',
    price: 768,
    recommendedGuestCount: 8,
    bedrooms: 2,
    beds: 8,
    baths: 1.7,
    imageUrl: 'http://dummyimage.com/184x100.png/ff4444/ffffff',
    reviews: {
      rating: 2,
      comment: 'A comment about my experience',
      userId: 100,
    },
    hostId: 31,
    street: '06 Novick Alley',
    city: 'Indianapolis',
    state: 'Indiana',
    zip: 28478,
    country: 'United States',
    address: {
      street: '06 Novick Alley',
      city: 'Indianapolis',
      state: 'Indiana',
      zip: 28478,
      country: 'United States',
    },
  },
  {
    name: 'Jazzy',
    description:
      'erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi',
    category: 'Desert',
    amenities: 'Cable',
    price: 115,
    recommendedGuestCount: 2,
    bedrooms: 4,
    beds: 6,
    baths: 3.5,
    imageUrl: 'http://dummyimage.com/224x100.png/dddddd/000000',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 95,
    },
    hostId: 18,
    street: '89 Maple Court',
    city: 'San Francisco',
    state: 'California',
    zip: 93895,
    country: 'United States',
    address: {
      street: '89 Maple Court',
      city: 'San Francisco',
      state: 'California',
      zip: 93895,
      country: 'United States',
    },
  },
  {
    name: 'Gabvine',
    description:
      'sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque',
    category: 'Desert',
    amenities: 'Cable',
    price: 864,
    recommendedGuestCount: 15,
    bedrooms: 4,
    beds: 10,
    baths: 3.5,
    imageUrl: 'http://dummyimage.com/159x100.png/cc0000/ffffff',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 41,
    },
    hostId: 6,
    street: '171 Anthes Way',
    city: 'Boston',
    state: 'Massachusetts',
    zip: 68872,
    country: 'United States',
    address: {
      street: '171 Anthes Way',
      city: 'Boston',
      state: 'Massachusetts',
      zip: 68872,
      country: 'United States',
    },
  },
  {
    name: 'InnoZ',
    description:
      'donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim',
    category: 'Woods',
    amenities: 'Cable',
    price: 274,
    recommendedGuestCount: 13,
    bedrooms: 1,
    beds: 4,
    baths: 3.5,
    imageUrl: 'http://dummyimage.com/184x100.png/ff4444/ffffff',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 18,
    },
    hostId: 84,
    street: '70162 Forster Circle',
    city: 'Simi Valley',
    state: 'California',
    zip: 13135,
    country: 'United States',
    address: {
      street: '70162 Forster Circle',
      city: 'Simi Valley',
      state: 'California',
      zip: 13135,
      country: 'United States',
    },
  },
  {
    name: 'Quinu',
    description:
      'lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu',
    category: 'Pool',
    amenities: 'Dishwasher',
    price: 244,
    recommendedGuestCount: 18,
    bedrooms: 2,
    beds: 10,
    baths: 3.8,
    imageUrl: 'http://dummyimage.com/150x100.png/dddddd/000000',
    reviews: {
      rating: 2,
      comment: 'A comment about my experience',
      userId: 94,
    },
    hostId: 10,
    street: '31431 Packers Drive',
    city: 'Phoenix',
    state: 'Arizona',
    zip: 97978,
    country: 'United States',
    address: {
      street: '31431 Packers Drive',
      city: 'Phoenix',
      state: 'Arizona',
      zip: 97978,
      country: 'United States',
    },
  },
  {
    name: 'Feedspan',
    description:
      'platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi',
    category: 'Castle',
    amenities: 'Security Cameras',
    price: 914,
    recommendedGuestCount: 9,
    bedrooms: 4,
    beds: 5,
    baths: 1.9,
    imageUrl: 'http://dummyimage.com/233x100.png/ff4444/ffffff',
    reviews: {
      rating: 2,
      comment: 'A comment about my experience',
      userId: 91,
    },
    hostId: 58,
    street: '3 Sommers Point',
    city: 'Tucson',
    state: 'Arizona',
    zip: 24333,
    country: 'United States',
    address: {
      street: '3 Sommers Point',
      city: 'Tucson',
      state: 'Arizona',
      zip: 24333,
      country: 'United States',
    },
  },
  {
    name: 'Kwilith',
    description:
      'nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor',
    category: 'Castle',
    amenities: 'WiFi',
    price: 933,
    recommendedGuestCount: 10,
    bedrooms: 4,
    beds: 6,
    baths: 3.6,
    imageUrl: 'http://dummyimage.com/147x100.png/cc0000/ffffff',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 89,
    },
    hostId: 53,
    street: '40313 Novick Place',
    city: 'Fort Wayne',
    state: 'Indiana',
    zip: 63039,
    country: 'United States',
    address: {
      street: '40313 Novick Place',
      city: 'Fort Wayne',
      state: 'Indiana',
      zip: 63039,
      country: 'United States',
    },
  },
  {
    name: 'Dabvine',
    description:
      'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis',
    category: 'Beach',
    amenities: 'Cable',
    price: 256,
    recommendedGuestCount: 1,
    bedrooms: 1,
    beds: 8,
    baths: 1.7,
    imageUrl: 'http://dummyimage.com/120x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 72,
    },
    hostId: 24,
    street: '4306 Anzinger Drive',
    city: 'Miami Beach',
    state: 'Florida',
    zip: 13628,
    country: 'United States',
    address: {
      street: '4306 Anzinger Drive',
      city: 'Miami Beach',
      state: 'Florida',
      zip: 13628,
      country: 'United States',
    },
  },
  {
    name: 'Devbug',
    description:
      'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti',
    category: 'Woods',
    amenities: 'Washing Machine/ Dryer',
    price: 219,
    recommendedGuestCount: 11,
    bedrooms: 2,
    beds: 7,
    baths: 4.2,
    imageUrl: 'http://dummyimage.com/159x100.png/dddddd/000000',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 29,
    },
    hostId: 78,
    street: '0339 Sunbrook Lane',
    city: 'Milwaukee',
    state: 'Wisconsin',
    zip: 72719,
    country: 'United States',
    address: {
      street: '0339 Sunbrook Lane',
      city: 'Milwaukee',
      state: 'Wisconsin',
      zip: 72719,
      country: 'United States',
    },
  },
  {
    name: 'Skilith',
    description:
      'vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae',
    category: 'Pool',
    amenities: 'Dishwasher',
    price: 743,
    recommendedGuestCount: 19,
    bedrooms: 3,
    beds: 9,
    baths: 1.1,
    imageUrl: 'http://dummyimage.com/236x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 1,
    },
    hostId: 27,
    street: '82 Stuart Lane',
    city: 'Cincinnati',
    state: 'Ohio',
    zip: 46320,
    country: 'United States',
    address: {
      street: '82 Stuart Lane',
      city: 'Cincinnati',
      state: 'Ohio',
      zip: 46320,
      country: 'United States',
    },
  },
  {
    name: 'Yakitri',
    description:
      'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue',
    category: 'Castle',
    amenities: 'Washing Machine/ Dryer',
    price: 843,
    recommendedGuestCount: 2,
    bedrooms: 5,
    beds: 10,
    baths: 3.6,
    imageUrl: 'http://dummyimage.com/185x100.png/ff4444/ffffff',
    reviews: {
      rating: 2,
      comment: 'A comment about my experience',
      userId: 2,
    },
    hostId: 60,
    street: '77 John Wall Terrace',
    city: 'Hartford',
    state: 'Connecticut',
    zip: 20919,
    country: 'United States',
    address: {
      street: '77 John Wall Terrace',
      city: 'Hartford',
      state: 'Connecticut',
      zip: 20919,
      country: 'United States',
    },
  },
  {
    name: 'Yadel',
    description:
      'libero ut massa volutpat convallis morbi odio odio elementum eu interdum',
    category: 'Beach',
    amenities: 'Dishwasher',
    price: 288,
    recommendedGuestCount: 13,
    bedrooms: 4,
    beds: 5,
    baths: 2.9,
    imageUrl: 'http://dummyimage.com/109x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 45,
    },
    hostId: 7,
    street: '60600 Packers Way',
    city: 'Houston',
    state: 'Texas',
    zip: 93677,
    country: 'United States',
    address: {
      street: '60600 Packers Way',
      city: 'Houston',
      state: 'Texas',
      zip: 93677,
      country: 'United States',
    },
  },
  {
    name: 'Skilith',
    description:
      'eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi',
    category: 'Castle',
    amenities: 'Security Cameras',
    price: 622,
    recommendedGuestCount: 10,
    bedrooms: 2,
    beds: 9,
    baths: 1.1,
    imageUrl: 'http://dummyimage.com/168x100.png/dddddd/000000',
    reviews: {
      rating: 2,
      comment: 'A comment about my experience',
      userId: 18,
    },
    hostId: 92,
    street: '46 Esch Plaza',
    city: 'Mansfield',
    state: 'Ohio',
    zip: 42236,
    country: 'United States',
    address: {
      street: '46 Esch Plaza',
      city: 'Mansfield',
      state: 'Ohio',
      zip: 42236,
      country: 'United States',
    },
  },
  {
    name: 'Zooveo',
    description:
      'odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus',
    category: 'Woods',
    amenities: 'Cable',
    price: 587,
    recommendedGuestCount: 5,
    bedrooms: 1,
    beds: 10,
    baths: 2.9,
    imageUrl: 'http://dummyimage.com/109x100.png/ff4444/ffffff',
    reviews: {
      rating: 1,
      comment: 'A comment about my experience',
      userId: 75,
    },
    hostId: 16,
    street: '8886 Loftsgordon Junction',
    city: 'Washington',
    state: 'District of Columbia',
    zip: 54467,
    country: 'United States',
    address: {
      street: '8886 Loftsgordon Junction',
      city: 'Washington',
      state: 'District of Columbia',
      zip: 54467,
      country: 'United States',
    },
  },
  {
    name: 'Blognation',
    description:
      'vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est',
    category: 'Woods',
    amenities: 'Washing Machine/ Dryer',
    price: 872,
    recommendedGuestCount: 8,
    bedrooms: 5,
    beds: 9,
    baths: 4.4,
    imageUrl: 'http://dummyimage.com/185x100.png/cc0000/ffffff',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 26,
    },
    hostId: 96,
    street: '1 Maryland Hill',
    city: 'Orlando',
    state: 'Florida',
    zip: 44499,
    country: 'United States',
    address: {
      street: '1 Maryland Hill',
      city: 'Orlando',
      state: 'Florida',
      zip: 44499,
      country: 'United States',
    },
  },
  {
    name: 'Teklist',
    description:
      'consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum',
    category: 'Pool',
    amenities: 'WiFi',
    price: 602,
    recommendedGuestCount: 3,
    bedrooms: 5,
    beds: 2,
    baths: 4.2,
    imageUrl: 'http://dummyimage.com/133x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 52,
    },
    hostId: 29,
    street: '4749 Springview Terrace',
    city: 'Toledo',
    state: 'Ohio',
    zip: 87099,
    country: 'United States',
    address: {
      street: '4749 Springview Terrace',
      city: 'Toledo',
      state: 'Ohio',
      zip: 87099,
      country: 'United States',
    },
  },
  {
    name: 'Mydo',
    description:
      'vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci',
    category: 'Woods',
    amenities: 'Dishwasher',
    price: 576,
    recommendedGuestCount: 20,
    bedrooms: 2,
    beds: 3,
    baths: 1.1,
    imageUrl: 'http://dummyimage.com/200x100.png/dddddd/000000',
    reviews: {
      rating: 2,
      comment: 'A comment about my experience',
      userId: 100,
    },
    hostId: 8,
    street: '689 Becker Hill',
    city: 'Hollywood',
    state: 'Florida',
    zip: 44313,
    country: 'United States',
    address: {
      street: '689 Becker Hill',
      city: 'Hollywood',
      state: 'Florida',
      zip: 44313,
      country: 'United States',
    },
  },
  {
    name: 'Zoonder',
    description:
      'in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo',
    category: 'Beach',
    amenities: 'Netflix',
    price: 920,
    recommendedGuestCount: 20,
    bedrooms: 4,
    beds: 7,
    baths: 1.9,
    imageUrl: 'http://dummyimage.com/181x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 10,
    },
    hostId: 71,
    street: '74 Tennyson Road',
    city: 'Harrisburg',
    state: 'Pennsylvania',
    zip: 81921,
    country: 'United States',
    address: {
      street: '74 Tennyson Road',
      city: 'Harrisburg',
      state: 'Pennsylvania',
      zip: 81921,
      country: 'United States',
    },
  },
  {
    name: 'Jabbersphere',
    description:
      'sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus',
    category: 'Woods',
    amenities: 'WiFi',
    price: 861,
    recommendedGuestCount: 10,
    bedrooms: 2,
    beds: 8,
    baths: 3.5,
    imageUrl: 'http://dummyimage.com/176x100.png/dddddd/000000',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 25,
    },
    hostId: 91,
    street: '44 Emmet Parkway',
    city: 'Roanoke',
    state: 'Virginia',
    zip: 37630,
    country: 'United States',
    address: {
      street: '44 Emmet Parkway',
      city: 'Roanoke',
      state: 'Virginia',
      zip: 37630,
      country: 'United States',
    },
  },
  {
    name: 'Yodoo',
    description:
      'risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero',
    category: 'Castle',
    amenities: 'Netflix',
    price: 746,
    recommendedGuestCount: 7,
    bedrooms: 3,
    beds: 10,
    baths: 1.9,
    imageUrl: 'http://dummyimage.com/107x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 1,
      comment: 'A comment about my experience',
      userId: 18,
    },
    hostId: 45,
    street: '7465 Monica Avenue',
    city: 'Biloxi',
    state: 'Mississippi',
    zip: 86429,
    country: 'United States',
    address: {
      street: '7465 Monica Avenue',
      city: 'Biloxi',
      state: 'Mississippi',
      zip: 86429,
      country: 'United States',
    },
  },
  {
    name: 'Blogtags',
    description:
      'in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis',
    category: 'Desert',
    amenities: 'WiFi',
    price: 332,
    recommendedGuestCount: 4,
    bedrooms: 1,
    beds: 3,
    baths: 4.0,
    imageUrl: 'http://dummyimage.com/100x100.png/dddddd/000000',
    reviews: {
      rating: 1,
      comment: 'A comment about my experience',
      userId: 96,
    },
    hostId: 42,
    street: '96396 John Wall Avenue',
    city: 'Alexandria',
    state: 'Virginia',
    zip: 54836,
    country: 'United States',
    address: {
      street: '96396 John Wall Avenue',
      city: 'Alexandria',
      state: 'Virginia',
      zip: 54836,
      country: 'United States',
    },
  },
  {
    name: 'Browsetype',
    description:
      'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed',
    category: 'Beach',
    amenities: 'Stocked Fridge',
    price: 956,
    recommendedGuestCount: 4,
    bedrooms: 1,
    beds: 3,
    baths: 2.3,
    imageUrl: 'http://dummyimage.com/124x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 2,
      comment: 'A comment about my experience',
      userId: 29,
    },
    hostId: 99,
    street: '60 Colorado Street',
    city: 'Dayton',
    state: 'Ohio',
    zip: 15455,
    country: 'United States',
    address: {
      street: '60 Colorado Street',
      city: 'Dayton',
      state: 'Ohio',
      zip: 15455,
      country: 'United States',
    },
  },
  {
    name: 'Divanoodle',
    description:
      'curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in',
    category: 'Pool',
    amenities: 'Netflix',
    price: 870,
    recommendedGuestCount: 13,
    bedrooms: 3,
    beds: 6,
    baths: 1.4,
    imageUrl: 'http://dummyimage.com/149x100.png/dddddd/000000',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 35,
    },
    hostId: 14,
    street: '78 Summer Ridge Place',
    city: 'Henderson',
    state: 'Nevada',
    zip: 80785,
    country: 'United States',
    address: {
      street: '78 Summer Ridge Place',
      city: 'Henderson',
      state: 'Nevada',
      zip: 80785,
      country: 'United States',
    },
  },
  {
    name: 'Geba',
    description:
      'eu est congue elementum in hac habitasse platea dictumst morbi',
    category: 'Woods',
    amenities: 'Netflix',
    price: 669,
    recommendedGuestCount: 14,
    bedrooms: 5,
    beds: 6,
    baths: 1.1,
    imageUrl: 'http://dummyimage.com/133x100.png/ff4444/ffffff',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 4,
    },
    hostId: 28,
    street: '49766 Lakewood Junction',
    city: 'Flint',
    state: 'Michigan',
    zip: 19546,
    country: 'United States',
    address: {
      street: '49766 Lakewood Junction',
      city: 'Flint',
      state: 'Michigan',
      zip: 19546,
      country: 'United States',
    },
  },
  {
    name: 'Devbug',
    description:
      'ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh',
    category: 'Beach',
    amenities: 'TV',
    price: 761,
    recommendedGuestCount: 12,
    bedrooms: 1,
    beds: 9,
    baths: 1.0,
    imageUrl: 'http://dummyimage.com/215x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 1,
      comment: 'A comment about my experience',
      userId: 91,
    },
    hostId: 97,
    street: '39 Forest Dale Avenue',
    city: 'Phoenix',
    state: 'Arizona',
    zip: 40557,
    country: 'United States',
    address: {
      street: '39 Forest Dale Avenue',
      city: 'Phoenix',
      state: 'Arizona',
      zip: 40557,
      country: 'United States',
    },
  },
  {
    name: 'Twinte',
    description:
      'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras',
    category: 'Castle',
    amenities: 'Stocked Fridge',
    price: 681,
    recommendedGuestCount: 12,
    bedrooms: 2,
    beds: 8,
    baths: 1.7,
    imageUrl: 'http://dummyimage.com/174x100.png/dddddd/000000',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 25,
    },
    hostId: 58,
    street: '5819 Hovde Road',
    city: 'San Francisco',
    state: 'California',
    zip: 29960,
    country: 'United States',
    address: {
      street: '5819 Hovde Road',
      city: 'San Francisco',
      state: 'California',
      zip: 29960,
      country: 'United States',
    },
  },
  {
    name: 'Avamm',
    description:
      'vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis',
    category: 'Desert',
    amenities: 'Security Cameras',
    price: 478,
    recommendedGuestCount: 18,
    bedrooms: 5,
    beds: 3,
    baths: 3.2,
    imageUrl: 'http://dummyimage.com/104x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 36,
    },
    hostId: 74,
    street: '63 Talisman Avenue',
    city: 'Memphis',
    state: 'Tennessee',
    zip: 90491,
    country: 'United States',
    address: {
      street: '63 Talisman Avenue',
      city: 'Memphis',
      state: 'Tennessee',
      zip: 90491,
      country: 'United States',
    },
  },
  {
    name: 'Zoomlounge',
    description:
      'est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci',
    category: 'Pool',
    amenities: 'Netflix',
    price: 338,
    recommendedGuestCount: 17,
    bedrooms: 1,
    beds: 10,
    baths: 4.3,
    imageUrl: 'http://dummyimage.com/231x100.png/ff4444/ffffff',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 87,
    },
    hostId: 53,
    street: '1 Fuller Park',
    city: 'San Diego',
    state: 'California',
    zip: 85781,
    country: 'United States',
    address: {
      street: '1 Fuller Park',
      city: 'San Diego',
      state: 'California',
      zip: 85781,
      country: 'United States',
    },
  },
  {
    name: 'Vidoo',
    description:
      'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque',
    category: 'Castle',
    amenities: 'Cable',
    price: 280,
    recommendedGuestCount: 1,
    bedrooms: 3,
    beds: 5,
    baths: 1.1,
    imageUrl: 'http://dummyimage.com/182x100.png/dddddd/000000',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 7,
    },
    hostId: 58,
    street: '2 Monument Center',
    city: 'Gastonia',
    state: 'North Carolina',
    zip: 41923,
    country: 'United States',
    address: {
      street: '2 Monument Center',
      city: 'Gastonia',
      state: 'North Carolina',
      zip: 41923,
      country: 'United States',
    },
  },
  {
    name: 'Roombo',
    description:
      'nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac',
    category: 'Pool',
    amenities: 'WiFi',
    price: 622,
    recommendedGuestCount: 8,
    bedrooms: 4,
    beds: 5,
    baths: 3.3,
    imageUrl: 'http://dummyimage.com/185x100.png/dddddd/000000',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 19,
    },
    hostId: 62,
    street: '9 Johnson Alley',
    city: 'Washington',
    state: 'District of Columbia',
    zip: 69042,
    country: 'United States',
    address: {
      street: '9 Johnson Alley',
      city: 'Washington',
      state: 'District of Columbia',
      zip: 69042,
      country: 'United States',
    },
  },
  {
    name: 'Shufflebeat',
    description:
      'nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in',
    category: 'Pool',
    amenities: 'Cable',
    price: 777,
    recommendedGuestCount: 18,
    bedrooms: 1,
    beds: 3,
    baths: 3.5,
    imageUrl: 'http://dummyimage.com/202x100.png/ff4444/ffffff',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 57,
    },
    hostId: 36,
    street: '03958 Katie Crossing',
    city: 'Norfolk',
    state: 'Virginia',
    zip: 10388,
    country: 'United States',
    address: {
      street: '03958 Katie Crossing',
      city: 'Norfolk',
      state: 'Virginia',
      zip: 10388,
      country: 'United States',
    },
  },
  {
    name: 'Oyonder',
    description:
      'aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus',
    category: 'Pool',
    amenities: 'TV',
    price: 108,
    recommendedGuestCount: 20,
    bedrooms: 1,
    beds: 6,
    baths: 2.9,
    imageUrl: 'http://dummyimage.com/145x100.png/ff4444/ffffff',
    reviews: {
      rating: 2,
      comment: 'A comment about my experience',
      userId: 9,
    },
    hostId: 82,
    street: '4113 Sutherland Place',
    city: 'Charleston',
    state: 'West Virginia',
    zip: 60412,
    country: 'United States',
    address: {
      street: '4113 Sutherland Place',
      city: 'Charleston',
      state: 'West Virginia',
      zip: 60412,
      country: 'United States',
    },
  },
  {
    name: 'Trudeo',
    description:
      'nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat',
    category: 'Beach',
    amenities: 'Washing Machine/ Dryer',
    price: 294,
    recommendedGuestCount: 2,
    bedrooms: 2,
    beds: 3,
    baths: 4.2,
    imageUrl: 'http://dummyimage.com/129x100.png/cc0000/ffffff',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 55,
    },
    hostId: 23,
    street: '859 Bellgrove Street',
    city: 'San Francisco',
    state: 'California',
    zip: 27165,
    country: 'United States',
    address: {
      street: '859 Bellgrove Street',
      city: 'San Francisco',
      state: 'California',
      zip: 27165,
      country: 'United States',
    },
  },
  {
    name: 'Jaxworks',
    description:
      'volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien',
    category: 'Beach',
    amenities: 'Security Cameras',
    price: 376,
    recommendedGuestCount: 4,
    bedrooms: 5,
    beds: 2,
    baths: 2.7,
    imageUrl: 'http://dummyimage.com/140x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 1,
      comment: 'A comment about my experience',
      userId: 30,
    },
    hostId: 58,
    street: '5 Nancy Trail',
    city: 'Lexington',
    state: 'Kentucky',
    zip: 70002,
    country: 'United States',
    address: {
      street: '5 Nancy Trail',
      city: 'Lexington',
      state: 'Kentucky',
      zip: 70002,
      country: 'United States',
    },
  },
  {
    name: 'Bluejam',
    description:
      'nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit',
    category: 'Castle',
    amenities: 'TV',
    price: 121,
    recommendedGuestCount: 12,
    bedrooms: 3,
    beds: 6,
    baths: 4.1,
    imageUrl: 'http://dummyimage.com/166x100.png/ff4444/ffffff',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 64,
    },
    hostId: 58,
    street: '7003 Warrior Parkway',
    city: 'Roanoke',
    state: 'Virginia',
    zip: 28025,
    country: 'United States',
    address: {
      street: '7003 Warrior Parkway',
      city: 'Roanoke',
      state: 'Virginia',
      zip: 28025,
      country: 'United States',
    },
  },
  {
    name: 'Quaxo',
    description:
      'quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien',
    category: 'Pool',
    amenities: 'Security Cameras',
    price: 198,
    recommendedGuestCount: 10,
    bedrooms: 5,
    beds: 4,
    baths: 4.9,
    imageUrl: 'http://dummyimage.com/131x100.png/dddddd/000000',
    reviews: {
      rating: 1,
      comment: 'A comment about my experience',
      userId: 22,
    },
    hostId: 69,
    street: '302 4th Crossing',
    city: 'Portland',
    state: 'Oregon',
    zip: 44896,
    country: 'United States',
    address: {
      street: '302 4th Crossing',
      city: 'Portland',
      state: 'Oregon',
      zip: 44896,
      country: 'United States',
    },
  },
  {
    name: 'Katz',
    description:
      'in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis',
    category: 'Castle',
    amenities: 'WiFi',
    price: 160,
    recommendedGuestCount: 10,
    bedrooms: 1,
    beds: 4,
    baths: 3.6,
    imageUrl: 'http://dummyimage.com/140x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 5,
      comment: 'A comment about my experience',
      userId: 56,
    },
    hostId: 8,
    street: '73791 Everett Court',
    city: 'Buffalo',
    state: 'New York',
    zip: 19008,
    country: 'United States',
    address: {
      street: '73791 Everett Court',
      city: 'Buffalo',
      state: 'New York',
      zip: 19008,
      country: 'United States',
    },
  },
  {
    name: 'Trudeo',
    description:
      'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi',
    category: 'Castle',
    amenities: 'TV',
    price: 264,
    recommendedGuestCount: 6,
    bedrooms: 5,
    beds: 1,
    baths: 3.2,
    imageUrl: 'http://dummyimage.com/103x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 4,
      comment: 'A comment about my experience',
      userId: 26,
    },
    hostId: 89,
    street: '177 Helena Hill',
    city: 'Boston',
    state: 'Massachusetts',
    zip: 12347,
    country: 'United States',
    address: {
      street: '177 Helena Hill',
      city: 'Boston',
      state: 'Massachusetts',
      zip: 12347,
      country: 'United States',
    },
  },
  {
    name: 'Zazio',
    description:
      'sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis',
    category: 'Beach',
    amenities: 'Washing Machine/ Dryer',
    price: 671,
    recommendedGuestCount: 1,
    bedrooms: 5,
    beds: 9,
    baths: 2.2,
    imageUrl: 'http://dummyimage.com/225x100.png/ff4444/ffffff',
    reviews: {
      rating: 0,
      comment: 'A comment about my experience',
      userId: 63,
    },
    hostId: 44,
    street: '2 Burrows Way',
    city: 'Durham',
    state: 'North Carolina',
    zip: 19035,
    country: 'United States',
    address: {
      street: '2 Burrows Way',
      city: 'Durham',
      state: 'North Carolina',
      zip: 19035,
      country: 'United States',
    },
  },
  {
    name: 'Zooxo',
    description:
      'quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor',
    category: 'Castle',
    amenities: 'Stocked Fridge',
    price: 659,
    recommendedGuestCount: 11,
    bedrooms: 5,
    beds: 7,
    baths: 2.0,
    imageUrl: 'http://dummyimage.com/247x100.png/ff4444/ffffff',
    reviews: {
      rating: 2,
      comment: 'A comment about my experience',
      userId: 19,
    },
    hostId: 53,
    street: '510 Weeping Birch Drive',
    city: 'Houston',
    state: 'Texas',
    zip: 56613,
    country: 'United States',
    address: {
      street: '510 Weeping Birch Drive',
      city: 'Houston',
      state: 'Texas',
      zip: 56613,
      country: 'United States',
    },
  },
  {
    name: 'Latz',
    description:
      'nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu',
    category: 'Pool',
    amenities: 'Stocked Fridge',
    price: 581,
    recommendedGuestCount: 12,
    bedrooms: 4,
    beds: 2,
    baths: 3.0,
    imageUrl: 'http://dummyimage.com/130x100.png/5fa2dd/ffffff',
    reviews: {
      rating: 3,
      comment: 'A comment about my experience',
      userId: 79,
    },
    hostId: 82,
    street: '699 Scofield Plaza',
    city: 'New York City',
    state: 'New York',
    zip: 82090,
    country: 'United States',
    address: {
      street: '699 Scofield Plaza',
      city: 'New York City',
      state: 'New York',
      zip: 82090,
      country: 'United States',
    },
  },
];
